# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f34ae149c075497f49efbcc14bde71ed3802f17c37be236aa999319fa259b979830ac368e2af5219191942fc1e06aeb07a97fd051e54fce45651aa749801b5f8

test:
  secret_key_base: 3e3ba09e8e81035bfa3cde3ef0cddf512bb57e28cc1e9b7f1b0a42d4c98fd43a80e0c812527916ee5162e25406e08f4c27b51eeaa2da228d643602446093ff5f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
